# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WeiBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeiBook
  pod 'Alamofire', '~> 4.4'
  pod 'SnapKit','~> 3.2.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'MBProgressHUD'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'DZNEmptyDataSet'
  pod 'ReactiveCocoa', '~> 5.0.2'
  pod 'ReactiveSwift', '~> 1.1'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FMDB'
  #    pod 'HanekeSwift'
  #    pod "Qiniu", "~> 7.1"
  pod 'JPush'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'AMapLocation' #定位SDK
  pod 'IQKeyboardManagerSwift', '4.0.9'

end
